# Generated by Django 5.0.2 on 2024-03-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_editor"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Editor",
            new_name="Autor",
        ),
    ]
